# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Create, Sign and Upload a build to alpha channel"
  lane :alpha do
    gradle(
        project_dir: "../../" ,
        task: "app:assembleLocalOld"
    )
    sh "~/.mozbuild/android-sdk-macosx/build-tools/25.0.3/zipalign -v -p 4 ~/cliqz-android/mozilla-release/objdir-frontend-android/gradle/build/mobile/android/app/outputs/apk/app-localOld-photon-release-unsigned.apk app-localOld-photon-release-unsigned-aligned.apk"
    sh "echo $CERT_PASS | ~/.mozbuild/android-sdk-macosx/build-tools/25.0.3/apksigner sign --ks $CERT_PATH --ks-key-alias browser --out app-localOld-photon-release.apk app-localOld-photon-release-unsigned-aligned.apk"
    upload_to_play_store(
      track:"alpha",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end
