# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define bookmarks_title Zakładki
#define bookmarks_heading Zakładki

#define bookmarks_toolbarfolder Folder zakładek osobistych
#define bookmarks_toolbarfolder_description Zakładki umieszczone w tym folderze będą widoczne na pasku zakładek.

#define getting_started Pierwsze kroki

#define firefox_heading Mozilla Firefox
#define firefox_help Pomoc
#define firefox_customize Dostosuj Firefoksa
#define firefox_community Dołącz do nas
#define firefox_about O Mozilli

#define nightly_heading Firefox Nightly
#define nightly_blog Blog Firefox Nightly
#define bugzilla Bugzilla - system obsługi błędów Mozilli
#define mdn Mozilla Developer Network
#define nightly_tester_tools Rozszerzenie Nightly Tester Tools
#define crashes Zgłoszenia awarii
#define irc Kanał IRC o Nightly
#define planet Planeta Mozilli

#unfilter emptyLines
